name: Build and deploy Docker Spring Boot app to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Enter environment variables in "application.properties"
      run: |
        sed -i 's%${DATABASE_STRING}%${{ secrets.DATABASE_STRING }}%g' src/main/resources/application.properties
        sed -i 's%${DATABASE_NAME}%${{ secrets.DATABASE_NAME }}%g' src/main/resources/application.properties
        sed -i 's%${DATABASE_PASSWORD}%${{ secrets.DATABASE_PASSWORD }}%g' src/main/resources/application.properties
        sed -i 's%${BLOB_STRING}%${{ secrets.BLOB_STRING }}%g' src/main/resources/application.properties
        sed -i 's%${BLOB_CONTAINER}%${{ secrets.BLOB_CONTAINER }}%g' src/main/resources/application.properties

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Grant "execute" permission for "gradlew"
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: index.docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:back
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'catphish-back-end'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:back'
